#!/usr/bin/env python3
"""Generate review-ready benchmark artifacts from saved pilot outputs.

This script intentionally uses only the Python standard library so it can run
in the lightweight review environment currently present in this repository.
Correctness labels are generated by a deterministic automatic grader; the
manual audit files reserve columns for later adjudication.
"""

from __future__ import annotations

import csv
import ctypes
import json
import math
import os
import re
import unicodedata
from collections import Counter, defaultdict
from decimal import Decimal, InvalidOperation
from html import escape
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("XDG_CACHE_HOME", "/tmp")
AR_PARSED = ROOT / "outputs" / "ar_parsed_generations.jsonl"
AR_RAW = ROOT / "outputs" / "ar_raw_generations.jsonl"
DLM_PARSED = ROOT / "dlm_outputs" / "dlm_parsed_generations.jsonl"
DLM_RAW = ROOT / "dlm_outputs" / "dlm_raw_generations.jsonl"
PILOT_DATA = ROOT / "PilotDataset.json"

DATA_DIR = ROOT / "data"
OUTPUTS_DIR = ROOT / "outputs"
METRICS_DIR = ROOT / "metrics"
FIG_DIR = ROOT / "fig_tabs"
DOCS_DIR = ROOT / "docs"

HIGH_CONFIDENCE_THRESHOLD = 0.90
ECE_BINS = 10


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    with path.open() as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in fieldnames})


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def normalized_text(value: object) -> str:
    if value is None:
        return ""
    text = unicodedata.normalize("NFKD", str(value)).encode("ascii", "ignore").decode("ascii")
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return " ".join(text.split())


def numeric_tokens(value: object) -> list[Decimal]:
    tokens = re.findall(r"[-+]?\d[\d,]*(?:\.\d+)?", str(value or ""))
    out = []
    for token in tokens:
        try:
            out.append(Decimal(token.replace(",", "")))
        except InvalidOperation:
            pass
    return out


def choice_map(prompt: str) -> dict[str, str]:
    out = {}
    for line in prompt.splitlines():
        m = re.match(r"^\s*([A-D])\s*[:.)]\s*(.+?)\s*$", line)
        if m:
            out[m.group(1)] = m.group(2)
    return out


def answer_letter(answer: object) -> str | None:
    text = str(answer or "").strip()
    patterns = [
        r"^\s*([A-D])\s*[:.)\s]",
        r"\boption\s+([A-D])\b",
        r"\banswer\s+is\s+([A-D])\b",
    ]
    for pattern in patterns:
        m = re.search(pattern, text, flags=re.IGNORECASE)
        if m:
            return m.group(1).upper()
    if re.fullmatch(r"[A-D]", text, flags=re.IGNORECASE):
        return text.upper()
    return None


def truth_values(ground_truth: object) -> list[str]:
    if isinstance(ground_truth, list):
        return [str(x) for x in ground_truth]
    if ground_truth is None:
        return []
    return [str(ground_truth)]


def auto_grade(row: dict) -> tuple[bool, str]:
    answer = row.get("answer")
    truths = truth_values(row.get("ground_truth"))
    answer_type = row.get("answer_type")
    prompt = row.get("prompt", "")

    if not answer or not truths:
        return False, "missing_answer_or_reference"

    if answer_type == "numeric":
        answer_nums = numeric_tokens(answer)
        truth_nums = [n for truth in truths for n in numeric_tokens(truth)]
        if answer_nums and truth_nums and answer_nums[-1] == truth_nums[-1]:
            return True, "numeric_last_value_match"
        return False, "numeric_last_value_mismatch"

    options = choice_map(prompt)
    letter = answer_letter(answer)
    if answer_type == "multiple_choice" and letter:
        normalized_truths = {normalized_text(t) for t in truths}
        if letter in normalized_truths:
            return True, "choice_letter_match"
        if letter in options and normalized_text(options[letter]) in normalized_truths:
            return True, "choice_option_text_match"

    norm_answer = normalized_text(answer)
    for truth in truths:
        norm_truth = normalized_text(truth)
        if norm_answer == norm_truth:
            return True, "string_exact_match"
        if norm_truth and (norm_truth in norm_answer or norm_answer in norm_truth):
            return True, "string_containment_match"

    return False, "string_mismatch"


def load_all_rows() -> tuple[list[dict], dict[str, int]]:
    sources = [
        ("outputs/ar_parsed_generations.jsonl", AR_PARSED, AR_RAW),
        ("dlm_outputs/dlm_parsed_generations.jsonl", DLM_PARSED, DLM_RAW),
    ]
    rows = []
    raw_counts = {}
    for source_name, parsed_path, raw_path in sources:
        parsed = read_jsonl(parsed_path)
        raw_counts[source_name] = sum(1 for line in raw_path.open() if line.strip())
        for row in parsed:
            row = dict(row)
            row["source_file"] = source_name
            row["model_id"] = row.get("model_name", "")
            row["model_family"] = row.get("model_architecture", "")
            row["prompt_condition"] = row.get("condition", "")
            row["parsed_confidence"] = float(row.get("confidence")) if row.get("confidence") is not None else None
            row["correct_auto"], row["grader_rule"] = auto_grade(row)
            rows.append(row)
    return rows, raw_counts


def mean(values: Iterable[float]) -> float | None:
    values = list(values)
    return sum(values) / len(values) if values else None


def ece(rows: list[dict], bins: int = ECE_BINS) -> float | None:
    usable = [r for r in rows if r.get("parsed_confidence") is not None and r.get("correct_auto") is not None]
    if not usable:
        return None
    total = len(usable)
    score = 0.0
    for b in range(bins):
        lo = b / bins
        hi = (b + 1) / bins
        if b == bins - 1:
            bucket = [r for r in usable if lo <= r["parsed_confidence"] <= hi]
        else:
            bucket = [r for r in usable if lo <= r["parsed_confidence"] < hi]
        if not bucket:
            continue
        acc = mean(1.0 if r["correct_auto"] else 0.0 for r in bucket)
        conf = mean(r["parsed_confidence"] for r in bucket)
        score += (len(bucket) / total) * abs(acc - conf)
    return score


def brier(rows: list[dict]) -> float | None:
    vals = []
    for r in rows:
        c = r.get("parsed_confidence")
        if c is not None and r.get("correct_auto") is not None:
            vals.append((c - (1.0 if r["correct_auto"] else 0.0)) ** 2)
    return mean(vals)


def auroc(rows: list[dict]) -> float | None:
    pos = [r["parsed_confidence"] for r in rows if r.get("parsed_confidence") is not None and r.get("correct_auto") is True]
    neg = [r["parsed_confidence"] for r in rows if r.get("parsed_confidence") is not None and r.get("correct_auto") is False]
    if not pos or not neg:
        return None
    wins = 0.0
    for p in pos:
        for n in neg:
            if p > n:
                wins += 1.0
            elif p == n:
                wins += 0.5
    return wins / (len(pos) * len(neg))


def metric_row(rows: list[dict], raw_count: int | None = None) -> dict:
    n = len(rows)
    correct = sum(1 for r in rows if r.get("correct_auto") is True)
    confs = [r["parsed_confidence"] for r in rows if r.get("parsed_confidence") is not None]
    hc_wrong = sum(
        1
        for r in rows
        if r.get("correct_auto") is False
        and r.get("parsed_confidence") is not None
        and r["parsed_confidence"] >= HIGH_CONFIDENCE_THRESHOLD
    )
    return {
        "N": n,
        "accuracy": correct / n if n else None,
        "mean_confidence": mean(confs),
        "expected_calibration_error": ece(rows),
        "brier_score": brier(rows),
        "area_under_roc": auroc(rows),
        "high_confidence_wrong_rate": hc_wrong / n if n else None,
        "parse_success": n / raw_count if raw_count else None,
    }


def fmt(value: object) -> object:
    if value is None:
        return "NA"
    if isinstance(value, float):
        return f"{value:.6f}"
    return value


def grouped(rows: list[dict], keys: tuple[str, ...]) -> dict[tuple, list[dict]]:
    out = defaultdict(list)
    for row in rows:
        out[tuple(row.get(k, "") for k in keys)].append(row)
    return dict(out)


def shared_question_ids(rows: list[dict]) -> set[str]:
    qsets = {
        family[0]: {r["question_id"] for r in rs}
        for family, rs in grouped(rows, ("model_family",)).items()
    }
    if {"AR", "DLM"} <= set(qsets):
        return qsets["AR"] & qsets["DLM"]
    return set().union(*qsets.values()) if qsets else set()


def produce_alignment_report(rows: list[dict], aligned_rows: list[dict]) -> None:
    report = []
    by_family = grouped(rows, ("model_family",))
    qsets = {family[0]: {r["question_id"] for r in rs} for family, rs in by_family.items()}
    if {"AR", "DLM"} <= set(qsets):
        ar_only = sorted(qsets["AR"] - qsets["DLM"])
        dlm_only = sorted(qsets["DLM"] - qsets["AR"])
        status = "pass" if not ar_only and not dlm_only else "fail"
        report.append({
            "check_name": "same_question_id_set_raw_sources",
            "status": status,
            "n_affected": len(ar_only) + len(dlm_only),
            "details": f"AR-only={len(ar_only)}; DLM-only={len(dlm_only)}",
        })
        write_csv(
            METRICS_DIR / "data_alignment_exclusions.csv",
            [{"question_id": qid, "excluded_from": "comparative_tables", "reason": "AR-only question_id"} for qid in ar_only]
            + [{"question_id": qid, "excluded_from": "comparative_tables", "reason": "DLM-only question_id"} for qid in dlm_only],
            ["question_id", "excluded_from", "reason"],
        )

    aligned_qsets = {
        family[0]: {r["question_id"] for r in rs}
        for family, rs in grouped(aligned_rows, ("model_family",)).items()
    }
    aligned_pass = len({frozenset(v) for v in aligned_qsets.values()}) <= 1
    report.append({
        "check_name": "same_question_id_set_comparative_analysis",
        "status": "pass" if aligned_pass else "fail",
        "n_affected": 0 if aligned_pass else 1,
        "details": f"{len(shared_question_ids(rows))} shared question_id values used for comparative tables and figures",
    })

    for label, keys in [
        ("duplicate_question_id_within_source", ("source_file", "question_id", "prompt_condition", "sample_id")),
    ]:
        counts = Counter(tuple(r.get(k, "") for k in keys) for r in rows)
        n = sum(v - 1 for v in counts.values() if v > 1)
        report.append({"check_name": label, "status": "pass" if n == 0 else "fail", "n_affected": n, "details": "duplicate full evaluation keys"})

    valid_datasets = {r["dataset"] for r in json.loads(PILOT_DATA.read_text())}
    valid_models = {"qwen/qwen-2.5-7b-instruct", "mercury-2"}
    valid_families = {"AR", "DLM"}
    valid_conditions = {"neutral", "cautious", "overconfident"}
    checks = [
        ("valid_dataset", lambda r: r.get("dataset") in valid_datasets),
        ("valid_model_id", lambda r: r.get("model_id") in valid_models),
        ("valid_model_family", lambda r: r.get("model_family") in valid_families),
        ("valid_prompt_condition", lambda r: r.get("prompt_condition") in valid_conditions),
        ("confidence_normalized_0_1", lambda r: isinstance(r.get("parsed_confidence"), float) and 0.0 <= r["parsed_confidence"] <= 1.0),
        ("correctness_binary_auto_label", lambda r: isinstance(r.get("correct_auto"), bool)),
    ]
    for name, predicate in checks:
        bad = [r for r in rows if not predicate(r)]
        report.append({"check_name": name, "status": "pass" if not bad else "fail", "n_affected": len(bad), "details": "" if not bad else "invalid rows present"})

    write_csv(METRICS_DIR / "data_alignment_report.csv", report, ["check_name", "status", "n_affected", "details"])


def produce_tables(rows: list[dict], raw_counts: dict[str, int]) -> None:
    table1 = []
    for (dataset, model, family, condition), rs in sorted(grouped(rows, ("dataset", "model_id", "model_family", "prompt_condition")).items()):
        table1.append({
            "dataset": dataset,
            "N": len(rs),
            "model": model,
            "family": family,
            "prompt_condition": condition,
            "confidence_scale": "verbalized probability in [0, 1]",
            "correctness_grader": "deterministic automatic string/numeric/choice grader",
            "metrics": "accuracy; mean confidence; expected calibration error; Brier score; area under the receiver operating characteristic curve; high-confidence wrong rate; parse success",
        })
    write_csv(FIG_DIR / "table_1_benchmark_specification.csv", table1, ["dataset", "N", "model", "family", "prompt_condition", "confidence_scale", "correctness_grader", "metrics"])

    table2 = []
    for (model, family, source_file), rs in sorted(grouped(rows, ("model_id", "model_family", "source_file")).items()):
        m = metric_row(rs, raw_counts.get(source_file))
        table2.append({"model": model, "family": family, **{k: fmt(v) for k, v in m.items()}})
    write_csv(FIG_DIR / "table_2_aggregate_metrics.csv", table2, ["model", "family", "N", "accuracy", "mean_confidence", "expected_calibration_error", "brier_score", "area_under_roc", "high_confidence_wrong_rate", "parse_success"])

    table3 = []
    for (dataset, model, family), rs in sorted(grouped(rows, ("dataset", "model_id", "model_family")).items()):
        m = metric_row(rs)
        table3.append({"dataset": dataset, "model": model, "family": family, **{k: fmt(v) for k, v in m.items() if k != "parse_success"}})
    write_csv(FIG_DIR / "table_3_per_dataset_metrics.csv", table3, ["dataset", "model", "family", "N", "accuracy", "mean_confidence", "expected_calibration_error", "brier_score", "area_under_roc", "high_confidence_wrong_rate"])

    table4 = []
    for (model, family, condition), rs in sorted(grouped(rows, ("model_id", "model_family", "prompt_condition")).items()):
        m = metric_row(rs)
        table4.append({"model": model, "family": family, "prompt_condition": condition, **{k: fmt(v) for k, v in m.items() if k not in {"area_under_roc", "parse_success"}}})
    write_csv(FIG_DIR / "table_4_prompt_condition_metrics.csv", table4, ["model", "family", "prompt_condition", "N", "accuracy", "mean_confidence", "expected_calibration_error", "brier_score", "high_confidence_wrong_rate"])


def reliability_points(rows: list[dict], family: str) -> list[tuple[float, float]]:
    rs = [r for r in rows if r["model_family"] == family]
    pts = []
    for b in range(ECE_BINS):
        lo, hi = b / ECE_BINS, (b + 1) / ECE_BINS
        if b == ECE_BINS - 1:
            bucket = [r for r in rs if lo <= r["parsed_confidence"] <= hi]
        else:
            bucket = [r for r in rs if lo <= r["parsed_confidence"] < hi]
        if bucket:
            pts.append((mean(r["parsed_confidence"] for r in bucket), mean(1.0 if r["correct_auto"] else 0.0 for r in bucket)))
    return pts


SVG_COLORS = {
    "Autoregressive (AR)": "#2f65a7",
    "Diffusion language model (DLM)": "#c45a3c",
    "AR: correct answers": "#2f65a7",
    "AR: wrong answers": "#91b8e8",
    "DLM: correct answers": "#c45a3c",
    "DLM: wrong answers": "#e6a18a",
}


def color_rgb(hex_color: str) -> tuple[float, float, float]:
    hex_color = hex_color.lstrip("#")
    return (
        int(hex_color[0:2], 16) / 255,
        int(hex_color[2:4], 16) / 255,
        int(hex_color[4:6], 16) / 255,
    )


class CairoTextExtents(ctypes.Structure):
    _fields_ = [
        ("x_bearing", ctypes.c_double),
        ("y_bearing", ctypes.c_double),
        ("width", ctypes.c_double),
        ("height", ctypes.c_double),
        ("x_advance", ctypes.c_double),
        ("y_advance", ctypes.c_double),
    ]


class CairoFigure:
    FORMAT_ARGB32 = 0
    FONT_SLANT_NORMAL = 0
    FONT_WEIGHT_NORMAL = 0
    FONT_WEIGHT_BOLD = 1

    def __init__(self, path: Path, width: int = 900, height: int = 560) -> None:
        self.path = path
        self.width = width
        self.height = height
        self.cairo = ctypes.CDLL("libcairo.so.2")
        self._bind()
        self.surface = self.cairo.cairo_image_surface_create(self.FORMAT_ARGB32, width, height)
        self.cr = self.cairo.cairo_create(self.surface)
        self.set_rgb("#ffffff")
        self.cairo.cairo_paint(self.cr)

    def _bind(self) -> None:
        c = self.cairo
        c.cairo_image_surface_create.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.c_int]
        c.cairo_image_surface_create.restype = ctypes.c_void_p
        c.cairo_create.argtypes = [ctypes.c_void_p]
        c.cairo_create.restype = ctypes.c_void_p
        c.cairo_destroy.argtypes = [ctypes.c_void_p]
        c.cairo_surface_destroy.argtypes = [ctypes.c_void_p]
        c.cairo_set_source_rgb.argtypes = [ctypes.c_void_p, ctypes.c_double, ctypes.c_double, ctypes.c_double]
        c.cairo_paint.argtypes = [ctypes.c_void_p]
        c.cairo_rectangle.argtypes = [ctypes.c_void_p, ctypes.c_double, ctypes.c_double, ctypes.c_double, ctypes.c_double]
        c.cairo_fill.argtypes = [ctypes.c_void_p]
        c.cairo_move_to.argtypes = [ctypes.c_void_p, ctypes.c_double, ctypes.c_double]
        c.cairo_line_to.argtypes = [ctypes.c_void_p, ctypes.c_double, ctypes.c_double]
        c.cairo_stroke.argtypes = [ctypes.c_void_p]
        c.cairo_set_line_width.argtypes = [ctypes.c_void_p, ctypes.c_double]
        c.cairo_set_dash.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_double), ctypes.c_int, ctypes.c_double]
        c.cairo_arc.argtypes = [ctypes.c_void_p, ctypes.c_double, ctypes.c_double, ctypes.c_double, ctypes.c_double, ctypes.c_double]
        c.cairo_select_font_face.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_int, ctypes.c_int]
        c.cairo_set_font_size.argtypes = [ctypes.c_void_p, ctypes.c_double]
        c.cairo_show_text.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
        c.cairo_text_extents.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.POINTER(CairoTextExtents)]
        c.cairo_save.argtypes = [ctypes.c_void_p]
        c.cairo_restore.argtypes = [ctypes.c_void_p]
        c.cairo_translate.argtypes = [ctypes.c_void_p, ctypes.c_double, ctypes.c_double]
        c.cairo_rotate.argtypes = [ctypes.c_void_p, ctypes.c_double]
        c.cairo_surface_write_to_png.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
        c.cairo_surface_write_to_png.restype = ctypes.c_int

    def set_rgb(self, color: str) -> None:
        self.cairo.cairo_set_source_rgb(self.cr, *color_rgb(color))

    def line(self, x0: float, y0: float, x1: float, y1: float, color: str = "#333333", width: float = 1.2, dash: tuple[float, ...] = ()) -> None:
        self.set_rgb(color)
        self.cairo.cairo_set_line_width(self.cr, width)
        if dash:
            arr = (ctypes.c_double * len(dash))(*dash)
            self.cairo.cairo_set_dash(self.cr, arr, len(dash), 0)
        else:
            self.cairo.cairo_set_dash(self.cr, None, 0, 0)
        self.cairo.cairo_move_to(self.cr, x0, y0)
        self.cairo.cairo_line_to(self.cr, x1, y1)
        self.cairo.cairo_stroke(self.cr)
        self.cairo.cairo_set_dash(self.cr, None, 0, 0)

    def rect(self, x: float, y: float, width: float, height: float, color: str) -> None:
        self.set_rgb(color)
        self.cairo.cairo_rectangle(self.cr, x, y, width, height)
        self.cairo.cairo_fill(self.cr)

    def circle(self, x: float, y: float, radius: float, color: str) -> None:
        self.set_rgb(color)
        self.cairo.cairo_arc(self.cr, x, y, radius, 0, 2 * math.pi)
        self.cairo.cairo_fill(self.cr)

    def text(self, x: float, y: float, value: str, size: float = 12, color: str = "#222222", align: str = "left", bold: bool = False, rotate: float = 0) -> None:
        encoded = str(value).encode("utf-8")
        self.cairo.cairo_save(self.cr)
        self.set_rgb(color)
        self.cairo.cairo_select_font_face(
            self.cr,
            b"DejaVu Sans",
            self.FONT_SLANT_NORMAL,
            self.FONT_WEIGHT_BOLD if bold else self.FONT_WEIGHT_NORMAL,
        )
        self.cairo.cairo_set_font_size(self.cr, size)
        ext = CairoTextExtents()
        self.cairo.cairo_text_extents(self.cr, encoded, ctypes.byref(ext))
        dx = 0
        if align == "center":
            dx = -ext.width / 2 - ext.x_bearing
        elif align == "right":
            dx = -ext.width - ext.x_bearing
        if rotate:
            self.cairo.cairo_translate(self.cr, x, y)
            self.cairo.cairo_rotate(self.cr, rotate)
            self.cairo.cairo_move_to(self.cr, dx, 0)
        else:
            self.cairo.cairo_move_to(self.cr, x + dx, y)
        self.cairo.cairo_show_text(self.cr, encoded)
        self.cairo.cairo_restore(self.cr)

    def write(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        status = self.cairo.cairo_surface_write_to_png(self.surface, str(self.path).encode("utf-8"))
        self.cairo.cairo_destroy(self.cr)
        self.cairo.cairo_surface_destroy(self.surface)
        if status != 0:
            raise RuntimeError(f"cairo_write_to_png failed for {self.path} with status {status}")


def draw_common_axes_png(fig: CairoFigure, left: int, right: int, top: int, bottom: int, x_label: str, y_label: str) -> None:
    for i in range(6):
        v = i / 5
        x, y = scale_point(v, v, left, right, top, bottom)
        fig.line(left, y, right, y, "#dddddd", 0.8)
        fig.line(x, top, x, bottom, "#dddddd", 0.8)
        fig.text(x, bottom + 22, f"{v:.1f}", 12, "#444444", align="center")
        fig.text(left - 12, y + 4, f"{v:.1f}", 12, "#444444", align="right")
    fig.line(left, bottom, right, bottom, "#333333", 1.2)
    fig.line(left, top, left, bottom, "#333333", 1.2)
    fig.text((left + right) / 2, bottom + 52, x_label, 15, align="center")
    fig.text(28, (top + bottom) / 2, y_label, 15, align="center", rotate=-math.pi / 2)


def draw_legend_png(fig: CairoFigure, labels: list[str], x: int, y: int) -> None:
    for i, label in enumerate(labels):
        yy = y + i * 24
        fig.rect(x, yy - 11, 15, 15, SVG_COLORS[label])
        fig.text(x + 23, yy + 1, label, 13)


def write_reliability_png(path: Path, rows: list[dict]) -> None:
    left, right, top, bottom = 92, 650, 72, 440
    fig = CairoFigure(path)
    fig.text(92, 34, "Reliability diagram", 20, bold=True)
    draw_common_axes_png(fig, left, right, top, bottom, "Mean verbalized confidence", "Empirical accuracy")
    x0, y0 = scale_point(0, 0, left, right, top, bottom)
    x1, y1 = scale_point(1, 1, left, right, top, bottom)
    fig.line(x0, y0, x1, y1, "#777777", 1.2, dash=(5, 5))
    labels = [("AR", "Autoregressive (AR)"), ("DLM", "Diffusion language model (DLM)")]
    for family, label in labels:
        pts = sorted(reliability_points(rows, family))
        color = SVG_COLORS[label]
        coords = [scale_point(x, y, left, right, top, bottom) for x, y in pts]
        for (px, py), (qx, qy) in zip(coords, coords[1:]):
            fig.line(px, py, qx, qy, color, 2.2)
        for x, y in coords:
            fig.circle(x, y, 4.2, color)
    draw_legend_png(fig, [label for _, label in labels], 690, 88)
    fig.text(690, 180, "Dashed line: perfect calibration", 13)
    fig.write()


def write_distribution_png(path: Path, rows: list[dict], title: str = "Reported confidence by answer outcome") -> None:
    left, right, top, bottom = 92, 720, 72, 440
    fig = CairoFigure(path)
    fig.text(92, 34, title, 20, bold=True)
    draw_common_axes_png(fig, left, right, top, bottom, "Reported confidence bin", "Share of answers in group")
    series = []
    for family, correct, label in [
        ("AR", True, "AR: correct answers"),
        ("AR", False, "AR: wrong answers"),
        ("DLM", True, "DLM: correct answers"),
        ("DLM", False, "DLM: wrong answers"),
    ]:
        sub = [r for r in rows if r["model_family"] == family and r["correct_auto"] is correct]
        denom = len(sub) or 1
        values = []
        for b in range(ECE_BINS):
            lo, hi = b / ECE_BINS, (b + 1) / ECE_BINS
            if b == ECE_BINS - 1:
                count = sum(1 for r in sub if lo <= r["parsed_confidence"] <= hi)
            else:
                count = sum(1 for r in sub if lo <= r["parsed_confidence"] < hi)
            values.append(count / denom)
        series.append((label, values))
    slot = (right - left) / ECE_BINS
    bar_w = slot / 5
    for sidx, (label, values) in enumerate(series):
        for b, value in enumerate(values):
            x = left + b * slot + (sidx + 0.45) * bar_w
            y = bottom - value * (bottom - top)
            fig.rect(x, y, bar_w, bottom - y, SVG_COLORS[label])
    draw_legend_png(fig, [label for label, _ in series], 742, 86)
    fig.write()


def write_prompt_sensitivity_png(path: Path, rows: list[dict]) -> None:
    left, right, top, bottom = 92, 720, 72, 440
    fig = CairoFigure(path)
    fig.text(92, 34, "Prompt sensitivity in expected calibration error", 20, bold=True)
    for i in range(6):
        v = i / 5
        y = bottom - v * (bottom - top)
        fig.line(left, y, right, y, "#dddddd", 0.8)
        fig.text(left - 12, y + 4, f"{v:.1f}", 12, "#444444", align="right")
    fig.line(left, bottom, right, bottom, "#333333", 1.2)
    fig.line(left, top, left, bottom, "#333333", 1.2)
    fig.text((left + right) / 2, bottom + 58, "Prompt condition", 15, align="center")
    fig.text(28, (top + bottom) / 2, "Expected calibration error", 15, align="center", rotate=-math.pi / 2)
    prompt_order = ["cautious", "neutral", "overconfident"]
    families = [("AR", "Autoregressive (AR)"), ("DLM", "Diffusion language model (DLM)")]
    slot = (right - left) / len(prompt_order)
    bar_w = slot / 4
    for fidx, (family, label) in enumerate(families):
        color = SVG_COLORS[label]
        for cidx, condition in enumerate(prompt_order):
            sub = [r for r in rows if r["model_family"] == family and r["prompt_condition"] == condition]
            value = ece(sub) or 0.0
            x = left + cidx * slot + (fidx + 1) * bar_w
            y = bottom - value * (bottom - top)
            fig.rect(x, y, bar_w, bottom - y, color)
    for cidx, condition in enumerate(prompt_order):
        cx = left + cidx * slot + slot / 2
        fig.text(cx, bottom + 24, condition, 12, "#444444", align="center")
    draw_legend_png(fig, [label for _, label in families], 742, 86)
    fig.write()


def svg_header(width: int, height: int) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <style>
    text {{ font-family: Arial, Helvetica, sans-serif; fill: #222; }}
    .title {{ font-size: 20px; font-weight: 600; }}
    .axis-label {{ font-size: 15px; }}
    .tick {{ font-size: 12px; fill: #444; }}
    .legend {{ font-size: 13px; }}
    .axis {{ stroke: #333; stroke-width: 1.2; }}
    .grid {{ stroke: #dddddd; stroke-width: 0.8; }}
  </style>
  <rect width="100%" height="100%" fill="#ffffff"/>
"""


def svg_footer() -> str:
    return "</svg>\n"


def write_svg(path: Path, body: str, width: int = 900, height: int = 560) -> None:
    write_text(path, svg_header(width, height) + body + svg_footer())


def scale_point(x: float, y: float, left: int, right: int, top: int, bottom: int) -> tuple[float, float]:
    sx = left + x * (right - left)
    sy = bottom - y * (bottom - top)
    return sx, sy


def axis_svg(left: int, right: int, top: int, bottom: int, x_label: str, y_label: str) -> str:
    parts = []
    for i in range(6):
        v = i / 5
        x, y = scale_point(v, v, left, right, top, bottom)
        parts.append(f'<line class="grid" x1="{left}" y1="{y:.1f}" x2="{right}" y2="{y:.1f}"/>')
        parts.append(f'<line class="grid" x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{bottom}"/>')
        parts.append(f'<text class="tick" x="{x:.1f}" y="{bottom + 22}" text-anchor="middle">{v:.1f}</text>')
        parts.append(f'<text class="tick" x="{left - 12}" y="{y + 4:.1f}" text-anchor="end">{v:.1f}</text>')
    parts.append(f'<line class="axis" x1="{left}" y1="{bottom}" x2="{right}" y2="{bottom}"/>')
    parts.append(f'<line class="axis" x1="{left}" y1="{top}" x2="{left}" y2="{bottom}"/>')
    parts.append(f'<text class="axis-label" x="{(left + right) / 2:.1f}" y="{bottom + 52}" text-anchor="middle">{escape(x_label)}</text>')
    parts.append(f'<text class="axis-label" transform="translate(28 {(top + bottom) / 2:.1f}) rotate(-90)" text-anchor="middle">{escape(y_label)}</text>')
    return "\n".join(parts)


def legend_svg(items: list[str], x: int, y: int) -> str:
    parts = []
    for i, label in enumerate(items):
        yy = y + i * 24
        color = SVG_COLORS[label]
        parts.append(f'<rect x="{x}" y="{yy - 11}" width="15" height="15" fill="{color}"/>')
        parts.append(f'<text class="legend" x="{x + 23}" y="{yy + 1}">{escape(label)}</text>')
    return "\n".join(parts)


def write_reliability_svg(path: Path, rows: list[dict]) -> None:
    left, right, top, bottom = 92, 650, 72, 440
    body = ['<text class="title" x="92" y="34">Reliability diagram</text>']
    body.append(axis_svg(left, right, top, bottom, "Mean verbalized confidence", "Empirical accuracy"))
    x0, y0 = scale_point(0, 0, left, right, top, bottom)
    x1, y1 = scale_point(1, 1, left, right, top, bottom)
    body.append(f'<line x1="{x0:.1f}" y1="{y0:.1f}" x2="{x1:.1f}" y2="{y1:.1f}" stroke="#777" stroke-width="1.2" stroke-dasharray="5 5"/>')
    labels = [("AR", "Autoregressive (AR)"), ("DLM", "Diffusion language model (DLM)")]
    for family, label in labels:
        pts = sorted(reliability_points(rows, family))
        color = SVG_COLORS[label]
        coords = [scale_point(x, y, left, right, top, bottom) for x, y in pts]
        if len(coords) > 1:
            points = " ".join(f"{x:.1f},{y:.1f}" for x, y in coords)
            body.append(f'<polyline points="{points}" fill="none" stroke="{color}" stroke-width="2.2"/>')
        for x, y in coords:
            body.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="4.2" fill="{color}"/>')
    body.append(legend_svg([label for _, label in labels], 690, 88))
    body.append('<text class="legend" x="690" y="180">Dashed line: perfect calibration</text>')
    write_svg(path, "\n".join(body))


def write_distribution_svg(path: Path, rows: list[dict], title: str = "Reported confidence by answer outcome") -> None:
    left, right, top, bottom = 92, 720, 72, 440
    body = [f'<text class="title" x="92" y="34">{escape(title)}</text>']
    body.append(axis_svg(left, right, top, bottom, "Reported confidence bin", "Share of answers in group"))
    series = []
    for family, correct, label in [
        ("AR", True, "AR: correct answers"),
        ("AR", False, "AR: wrong answers"),
        ("DLM", True, "DLM: correct answers"),
        ("DLM", False, "DLM: wrong answers"),
    ]:
        sub = [r for r in rows if r["model_family"] == family and r["correct_auto"] is correct]
        denom = len(sub) or 1
        values = []
        for b in range(ECE_BINS):
            lo, hi = b / ECE_BINS, (b + 1) / ECE_BINS
            if b == ECE_BINS - 1:
                count = sum(1 for r in sub if lo <= r["parsed_confidence"] <= hi)
            else:
                count = sum(1 for r in sub if lo <= r["parsed_confidence"] < hi)
            values.append(count / denom)
        series.append((label, values))
    slot = (right - left) / ECE_BINS
    bar_w = slot / 5
    for sidx, (label, values) in enumerate(series):
        color = SVG_COLORS[label]
        for b, value in enumerate(values):
            x = left + b * slot + (sidx + 0.45) * bar_w
            y = bottom - value * (bottom - top)
            body.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{bottom - y:.1f}" fill="{color}"/>')
    body.append(legend_svg([label for label, _ in series], 742, 86))
    write_svg(path, "\n".join(body))


def write_prompt_sensitivity_svg(path: Path, rows: list[dict]) -> None:
    left, right, top, bottom = 92, 720, 72, 440
    body = ['<text class="title" x="92" y="34">Prompt sensitivity in expected calibration error</text>']
    for i in range(6):
        v = i / 5
        y = bottom - v * (bottom - top)
        body.append(f'<line class="grid" x1="{left}" y1="{y:.1f}" x2="{right}" y2="{y:.1f}"/>')
        body.append(f'<text class="tick" x="{left - 12}" y="{y + 4:.1f}" text-anchor="end">{v:.1f}</text>')
    body.append(f'<line class="axis" x1="{left}" y1="{bottom}" x2="{right}" y2="{bottom}"/>')
    body.append(f'<line class="axis" x1="{left}" y1="{top}" x2="{left}" y2="{bottom}"/>')
    body.append(f'<text class="axis-label" x="{(left + right) / 2:.1f}" y="{bottom + 58}" text-anchor="middle">Prompt condition</text>')
    body.append(f'<text class="axis-label" transform="translate(28 {(top + bottom) / 2:.1f}) rotate(-90)" text-anchor="middle">Expected calibration error</text>')
    prompt_order = ["cautious", "neutral", "overconfident"]
    families = [("AR", "Autoregressive (AR)"), ("DLM", "Diffusion language model (DLM)")]
    slot = (right - left) / len(prompt_order)
    bar_w = slot / 4
    for fidx, (family, label) in enumerate(families):
        color = SVG_COLORS[label]
        for cidx, condition in enumerate(prompt_order):
            sub = [r for r in rows if r["model_family"] == family and r["prompt_condition"] == condition]
            value = ece(sub) or 0.0
            x = left + cidx * slot + (fidx + 1) * bar_w
            y = bottom - value * (bottom - top)
            body.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{bottom - y:.1f}" fill="{color}"/>')
    for cidx, condition in enumerate(prompt_order):
        cx = left + cidx * slot + slot / 2
        body.append(f'<text class="tick" x="{cx:.1f}" y="{bottom + 24}" text-anchor="middle">{escape(condition)}</text>')
    body.append(legend_svg([label for _, label in families], 742, 86))
    write_svg(path, "\n".join(body))


def produce_figures(rows: list[dict]) -> None:
    write_reliability_png(FIG_DIR / "figure_1_reliability_diagram.png", rows)
    write_text(
        FIG_DIR / "figure_1_caption.txt",
        "Figure 1. Reliability diagram using 10 equal-width bins of verbalized confidence normalized to [0, 1]. Empty bins are omitted. The dashed diagonal denotes perfect calibration, where empirical accuracy equals mean confidence. Curves compare qwen/qwen-2.5-7b-instruct, an autoregressive language model (AR), and mercury-2, a diffusion language model (DLM), using deterministic rule-based correctness labels.\n",
    )

    write_distribution_png(FIG_DIR / "figure_2_confidence_by_correctness.png", rows)
    write_text(
        FIG_DIR / "figure_2_caption.txt",
        "Figure 2. Reported confidence distributions for correct and wrong answers. The x-axis bins each model answer by its reported confidence on the normalized [0, 1] scale. The y-axis gives the share of answers from the indicated group that fall in each confidence bin; within each legend group, the bars sum to one across bins. Correct and wrong answers are assigned by the deterministic rule-based grader described in the benchmark specification. AR denotes the autoregressive language model and DLM denotes the diffusion language model. A concentration of wrong-answer bars near confidence 1.0 indicates high-confidence errors.\n",
    )

    neutral_rows = [r for r in rows if r["prompt_condition"] == "neutral"]
    write_distribution_png(
        FIG_DIR / "figure_2_2_confidence_by_correctness_neutral.png",
        neutral_rows,
        "Reported confidence by answer outcome: neutral prompt",
    )
    write_text(
        FIG_DIR / "figure_2_2_caption.txt",
        "Figure 2.2. Reported confidence distributions for correct and wrong answers under the neutral prompt only. The x-axis bins each model answer by its reported confidence on the normalized [0, 1] scale. The y-axis gives the share of answers from the indicated group that fall in each confidence bin; within each legend group, the bars sum to one across bins. Correct and wrong answers are assigned by the deterministic rule-based grader described in the benchmark specification. This neutral-only comparison controls the prompt condition across the autoregressive language model (AR) and diffusion language model (DLM), so it is the most relevant version of the distributional plot for comparing model families without pooling over cautious and overconfident prompt interventions.\n",
    )

    write_prompt_sensitivity_png(FIG_DIR / "figure_3_prompt_sensitivity.png", rows)
    write_text(
        FIG_DIR / "figure_3_caption.txt",
        "Figure 3. Prompt sensitivity measured by expected calibration error. Expected calibration error is computed with 10 equal-width bins of verbalized confidence normalized to [0, 1]. The x-axis gives the prompt condition and the y-axis gives expected calibration error. Bars compare the autoregressive language model (AR) and diffusion language model (DLM) on the shared question-ID analysis set.\n",
    )


def produce_table_captions() -> None:
    captions = {
        "table_1_caption.txt": "Table 1. Benchmark specification by dataset, model, model family, and prompt condition. N is the number of parsed generations in the aligned comparative analysis set.\n",
        "table_2_caption.txt": "Table 2. Aggregate calibration metrics for the autoregressive language model (AR) and diffusion language model (DLM). Expected calibration error uses 10 equal-width confidence bins; area under the receiver operating characteristic curve is abbreviated as AUROC.\n",
        "table_3_caption.txt": "Table 3. Dataset-level calibration metrics by model family. Metrics are computed on parsed generations from the shared question-ID analysis set.\n",
        "table_4_caption.txt": "Table 4. Prompt-condition calibration metrics. Expected calibration error and high-confidence wrong rate quantify sensitivity to cautious, neutral, and overconfident prompting.\n",
        "table_5_caption.txt": "Table 5. Representative cases selected for qualitative audit. Correctness reflects deterministic automatic grading and should be adjudicated before being used as final qualitative evidence.\n",
    }
    for filename, caption in captions.items():
        write_text(FIG_DIR / filename, caption)


def short(value: object, n: int = 140) -> str:
    text = " ".join(str(value or "").split())
    return text if len(text) <= n else text[: n - 3] + "..."


def produce_audit_and_cases(rows: list[dict]) -> None:
    confidence_change_rows = []
    for (_model, _family, _qid, _sample, _answer, _correct), group in grouped(
        rows,
        ("model_id", "model_family", "question_id", "sample_id", "answer", "correct_auto"),
    ).items():
        conditions = {r["prompt_condition"] for r in group}
        confs = [r["parsed_confidence"] for r in group if r.get("parsed_confidence") is not None]
        if len(conditions) >= 2 and confs and max(confs) - min(confs) >= 0.20:
            chosen = max(group, key=lambda r: r["parsed_confidence"])
            confidence_change_rows.append(chosen)

    audit_rows = []
    row_categories = [
        ("high_confidence_wrong", lambda r: not r["correct_auto"] and r["parsed_confidence"] >= HIGH_CONFIDENCE_THRESHOLD),
        ("low_confidence_correct", lambda r: r["correct_auto"] and r["parsed_confidence"] <= 0.5),
        ("answer_and_reasoning_mismatch", lambda r: False),
        ("ambiguous_grading_case", lambda r: r["grader_rule"] in {"string_containment_match", "string_mismatch"}),
        ("random_example", lambda r: True),
    ]
    used = set()
    for category, predicate in row_categories:
        selected = [r for r in rows if predicate(r) and id(r) not in used][:10]
        for r in selected:
            used.add(id(r))
            audit_rows.append({
                "question_id": r["question_id"],
                "dataset": r["dataset"],
                "model": r["model_id"],
                "family": r["model_family"],
                "prompt_condition": r["prompt_condition"],
                "model_answer": short(r.get("answer"), 300),
                "gold_answer": short(r.get("ground_truth"), 300),
                "automatic_grade": int(bool(r["correct_auto"])),
                "manual_grade": "pending",
                "issue_type": category,
                "notes": f"automatic grader rule: {r['grader_rule']}",
            })
    for r in confidence_change_rows[:10]:
        audit_rows.append({
            "question_id": r["question_id"],
            "dataset": r["dataset"],
            "model": r["model_id"],
            "family": r["model_family"],
            "prompt_condition": "cross-condition",
            "model_answer": short(r.get("answer"), 300),
            "gold_answer": short(r.get("ground_truth"), 300),
            "automatic_grade": int(bool(r["correct_auto"])),
            "manual_grade": "pending",
            "issue_type": "confidence_changes_without_correctness_changes",
            "notes": "same answer and rule-based correctness label observed with >=0.20 confidence range across prompt conditions",
        })
    write_csv(METRICS_DIR / "manual_grading_audit.csv", audit_rows, ["question_id", "dataset", "model", "family", "prompt_condition", "model_answer", "gold_answer", "automatic_grade", "manual_grade", "issue_type", "notes"])

    summary = []
    counts = Counter(r["issue_type"] for r in audit_rows)
    for category in [
        "high_confidence_wrong",
        "low_confidence_correct",
        "answer_and_reasoning_mismatch",
        "confidence_changes_without_correctness_changes",
        "ambiguous_grading_case",
        "random_example",
    ]:
        summary.append({"audit_category": category, "N": counts[category], "agreement_rate": "NA", "main_issue": "manual adjudication not yet performed"})
    write_csv(FIG_DIR / "manual_grading_audit_summary.csv", summary, ["audit_category", "N", "agreement_rate", "main_issue"])

    cases = []
    case_sources = {
        "high_confidence_wrong": [r for r in rows if not r["correct_auto"] and r["parsed_confidence"] >= HIGH_CONFIDENCE_THRESHOLD],
        "low_confidence_correct": [r for r in rows if r["correct_auto"] and r["parsed_confidence"] <= 0.5],
        "confidence_change_without_answer_change": confidence_change_rows,
        "ambiguous_correctness_label": [r for r in rows if r["grader_rule"] in {"string_containment_match", "string_mismatch"}],
    }
    for category, source in case_sources.items():
        for r in source[:3]:
            cases.append({
                "model": r["model_id"],
                "family": r["model_family"],
                "prompt": r["prompt_condition"] if category != "confidence_change_without_answer_change" else "cross-condition",
                "dataset": r["dataset"],
                "question_short": short(r.get("prompt"), 180),
                "answer": short(r.get("answer"), 300),
                "confidence": r["parsed_confidence"],
                "correctness": int(bool(r["correct_auto"])),
                "failure_type": category,
                "short_interpretation": "Selected for manual review; interpretation should be finalized after adjudication.",
            })
    if not case_sources["low_confidence_correct"]:
        cases.append({
            "model": "NA",
            "family": "NA",
            "prompt": "NA",
            "dataset": "NA",
            "question_short": "No low-confidence correct case was found under confidence <= 0.50.",
            "answer": "NA",
            "confidence": "NA",
            "correctness": "NA",
            "failure_type": "low_confidence_correct",
            "short_interpretation": "Not present in the saved aligned outputs under the predefined threshold.",
        })
    for category in ["answer_and_reasoning_mismatch"]:
        cases.append({
            "model": "NA",
            "family": "NA",
            "prompt": "NA",
            "dataset": "NA",
            "question_short": "No reliable automatic detector in saved outputs.",
            "answer": "NA",
            "confidence": "NA",
            "correctness": "NA",
            "failure_type": category,
            "short_interpretation": "Requires manual qualitative coding.",
        })
    write_csv(FIG_DIR / "table_5_representative_failure_cases.csv", cases, ["model", "family", "prompt", "dataset", "question_short", "answer", "confidence", "correctness", "failure_type", "short_interpretation"])


def produce_docs(rows: list[dict], raw_counts: dict[str, int]) -> None:
    datasets = sorted({r["dataset"] for r in rows})
    models = sorted({r["model_id"] for r in rows})
    conditions = sorted({r["prompt_condition"] for r in rows})
    n_shared_questions = len(shared_question_ids(rows))
    spec = f"""# Benchmark Specification

## Benchmark Objective

Evaluate whether verbalized confidence tracks answer correctness under controlled prompting, comparing an autoregressive language model with a diffusion language model.

## Construct

The measured construct is verbalized confidence calibration: the correspondence between a model's stated confidence probability and empirical correctness.

## Unit of Evaluation

One model generation for one `question_id`, prompt condition, and sample index.

Comparative metric tables and figures use the shared AR/DLM question-ID intersection ({n_shared_questions} questions). Source-level exclusions are listed in `metrics/data_alignment_exclusions.csv`.

## Datasets

{', '.join(datasets)}

## Model Identifiers

{', '.join(models)}

## Model Family Labels

`AR` denotes an autoregressive language model. `DLM` denotes a diffusion language model.

## Prompt Conditions

{', '.join(conditions)}

## Confidence Scale

Models report a verbalized confidence probability in `[0, 1]`. Values outside this interval fail quality control.

## Correctness Grader

The saved parsed outputs do not contain human or LLM-judge correctness labels. This artifact therefore uses a deterministic automatic grader: last-number matching for numeric answers, option-letter or option-text matching for multiple-choice answers, and normalized string exact/containment matching for short answers. These labels are suitable for artifact execution checks and preliminary benchmarking, but they should be replaced or audited for final claims.

## Metric Definitions

Accuracy is the fraction of automatically correct generations. Mean confidence is the arithmetic mean of verbalized confidence. Expected calibration error (ECE) uses {ECE_BINS} equal-width confidence bins and weights each absolute bin accuracy-confidence gap by bin frequency. Brier score is the mean squared error between confidence and correctness. Area under the receiver operating characteristic curve (AUROC) is the Mann-Whitney probability that a correct generation receives higher confidence than an incorrect generation, with half credit for ties. High-confidence wrong rate is the fraction of all evaluated generations that are incorrect with confidence >= {HIGH_CONFIDENCE_THRESHOLD:.2f}. Parse success is parsed rows divided by raw rows for each model source.

## Quality Control Checks

The artifact checks question-ID alignment by model family, duplicate full evaluation keys, dataset validity, model identifier validity, family-label validity, prompt-condition validity, confidence range, and binary rule-based correctness labels.

## Known Limitations

DLM outputs are incomplete relative to the full AR question set, so comparative outputs use the shared question-ID intersection. Correctness labels are deterministic automatic labels rather than manual adjudications. Prompt sensitivity is therefore reported as an available-case analysis over parsed rows within the aligned question set. Some short-answer datasets require semantic grading beyond normalized string matching.
"""
    write_text(DOCS_DIR / "benchmark_spec.md", spec)

    readme = f"""# Review Artifact

This artifact contains saved AR and DLM generations, benchmark specifications, metric tables, figures, captions, schema documentation, and audit templates for the verbalized confidence calibration benchmark.

Comparative tables and figures are computed on the shared AR/DLM question-ID intersection. Raw-source exclusions are documented in `metrics/data_alignment_exclusions.csv`.

## Reproduction

From the repository root, run:

```bash
python3 src/prepare_review_artifact.py
```

The script reads `outputs/ar_parsed_generations.jsonl`, `outputs/ar_raw_generations.jsonl`, `dlm_outputs/dlm_parsed_generations.jsonl`, `dlm_outputs/dlm_raw_generations.jsonl`, and `PilotDataset.json`. It writes tables and figure files to `fig_tabs/`, quality-control reports to `metrics/`, and release metadata to `docs/`.

## Raw and Parsed Outputs

AR outputs are stored in `outputs/`. DLM outputs are stored in `dlm_outputs/`.

## Confidence Parsing

Each parsed generation contains `confidence`, a verbalized probability normalized to `[0, 1]`.

## Correctness Grading

The current artifact uses deterministic automatic grading because saved parsed outputs do not include adjudicated correctness labels. Numeric answers use last-number matching; multiple-choice answers use option-letter or option-text matching; short answers use normalized string matching and containment.

## Prompt Conditions

Prompt conditions are encoded in the `condition` field as `neutral`, `cautious`, or `overconfident`.

## Not Included

This package does not include API keys, private links, author-identifying metadata, or completed manual adjudication labels.

## Anonymity

The review materials are prepared without author names, institution names, private URLs, API keys, or workspace-specific absolute paths.
"""
    write_text(DOCS_DIR / "artifact_readme.md", readme)

    data_manifest = [
        {"file_path": "PilotDataset.json", "description": "Benchmark item source file", "row_count": len(json.loads(PILOT_DATA.read_text()))},
        {"file_path": "outputs/ar_raw_generations.jsonl", "description": "AR raw model outputs", "row_count": raw_counts["outputs/ar_parsed_generations.jsonl"]},
        {"file_path": "outputs/ar_parsed_generations.jsonl", "description": "AR parsed generations", "row_count": sum(1 for r in rows if r["model_family"] == "AR")},
        {"file_path": "dlm_outputs/dlm_raw_generations.jsonl", "description": "DLM raw model outputs", "row_count": raw_counts["dlm_outputs/dlm_parsed_generations.jsonl"]},
        {"file_path": "dlm_outputs/dlm_parsed_generations.jsonl", "description": "DLM parsed generations", "row_count": sum(1 for r in rows if r["model_family"] == "DLM")},
    ]
    write_csv(DOCS_DIR / "data_manifest.csv", data_manifest, ["file_path", "description", "row_count"])


def produce_schema_files() -> None:
    schemas = {
        "schema_benchmark_items.json": {
            "type": "object",
            "required": ["question_id", "dataset", "split", "question", "gold_answer", "answer_type", "domain", "source", "license"],
            "properties": {k: {"type": "string"} for k in ["question_id", "dataset", "split", "question", "gold_answer", "answer_type", "domain", "source", "license"]},
        },
        "schema_generations.json": {
            "type": "object",
            "required": ["question_id", "dataset", "model_id", "model_family", "provider", "prompt_id", "prompt_condition", "raw_output", "parsed_answer", "parsed_confidence", "parsed_reasoning", "parse_success", "parse_error_type", "correct_auto", "correct_manual", "grader", "temperature", "max_tokens", "seed", "timestamp"],
            "properties": {
                "parsed_confidence": {"type": ["number", "null"], "minimum": 0, "maximum": 1},
                "parse_success": {"type": "boolean"},
                "correct_auto": {"type": ["boolean", "null"]},
                "correct_manual": {"type": ["boolean", "null"]},
            },
        },
        "schema_metrics.json": {
            "type": "object",
            "required": ["model_id", "model_family", "prompt_condition", "dataset", "N", "accuracy", "mean_confidence", "expected_calibration_error", "brier_score", "area_under_roc", "high_confidence_wrong_rate", "parse_success"],
            "properties": {
                "N": {"type": "integer", "minimum": 0},
                "accuracy": {"type": ["number", "null"], "minimum": 0, "maximum": 1},
                "mean_confidence": {"type": ["number", "null"], "minimum": 0, "maximum": 1},
                "expected_calibration_error": {"type": ["number", "null"], "minimum": 0, "maximum": 1},
                "brier_score": {"type": ["number", "null"], "minimum": 0, "maximum": 1},
                "area_under_roc": {"type": ["number", "null"], "minimum": 0, "maximum": 1},
                "high_confidence_wrong_rate": {"type": ["number", "null"], "minimum": 0, "maximum": 1},
                "parse_success": {"type": ["number", "null"], "minimum": 0, "maximum": 1},
            },
        },
    }
    for name, schema in schemas.items():
        write_text(DOCS_DIR / name, json.dumps(schema, indent=2) + "\n")


def produce_manifest() -> None:
    entries = []
    definitions = [
        ("PilotDataset.json", "data", "Benchmark item source file", "Benchmark", True, True),
        ("outputs/ar_raw_generations.jsonl", "raw_output", "Autoregressive raw generations", "Artifact", True, True),
        ("outputs/ar_parsed_generations.jsonl", "parsed_output", "Autoregressive parsed generations", "Artifact", True, True),
        ("dlm_outputs/dlm_raw_generations.jsonl", "raw_output", "Diffusion language model raw generations", "Artifact", True, True),
        ("dlm_outputs/dlm_parsed_generations.jsonl", "parsed_output", "Diffusion language model parsed generations", "Artifact", True, True),
        ("metrics/data_alignment_report.csv", "audit", "Data alignment and schema quality-control checks", "Benchmark", True, True),
        ("metrics/data_alignment_exclusions.csv", "audit", "Question IDs excluded from comparative aligned analysis", "Benchmark", True, True),
        ("metrics/manual_grading_audit.csv", "audit", "Manual grading audit template with selected examples", "Analysis", True, False),
        ("fig_tabs/table_1_benchmark_specification.csv", "metric_table", "Benchmark specification table", "Benchmark", True, True),
        ("fig_tabs/table_2_aggregate_metrics.csv", "metric_table", "Aggregate AR versus DLM metrics", "Results", True, True),
        ("fig_tabs/table_3_per_dataset_metrics.csv", "metric_table", "Dataset-level metrics", "Results", True, True),
        ("fig_tabs/table_4_prompt_condition_metrics.csv", "metric_table", "Prompt-condition metrics", "Results", True, True),
        ("fig_tabs/table_5_representative_failure_cases.csv", "metric_table", "Representative qualitative cases", "Analysis", True, False),
        ("fig_tabs/table_1_caption.txt", "caption", "Benchmark specification table caption", "Benchmark", True, True),
        ("fig_tabs/table_2_caption.txt", "caption", "Aggregate metric table caption", "Results", True, True),
        ("fig_tabs/table_3_caption.txt", "caption", "Dataset-level metric table caption", "Results", True, True),
        ("fig_tabs/table_4_caption.txt", "caption", "Prompt-condition metric table caption", "Results", True, True),
        ("fig_tabs/table_5_caption.txt", "caption", "Representative case table caption", "Analysis", True, True),
        ("fig_tabs/figure_1_reliability_diagram.png", "figure", "Reliability diagram", "Results", True, True),
        ("fig_tabs/figure_1_caption.txt", "caption", "Reliability diagram caption", "Results", True, True),
        ("fig_tabs/figure_2_confidence_by_correctness.png", "figure", "Confidence distribution by correctness", "Results", True, True),
        ("fig_tabs/figure_2_caption.txt", "caption", "Confidence distribution caption", "Results", True, True),
        ("fig_tabs/figure_2_2_confidence_by_correctness_neutral.png", "figure", "Neutral-prompt confidence distribution by correctness", "Results", True, True),
        ("fig_tabs/figure_2_2_caption.txt", "caption", "Neutral-prompt confidence distribution caption", "Results", True, True),
        ("fig_tabs/figure_3_prompt_sensitivity.png", "figure", "Prompt sensitivity figure", "Results", True, True),
        ("fig_tabs/figure_3_caption.txt", "caption", "Prompt sensitivity caption", "Results", True, True),
        ("docs/artifact_manifest.csv", "documentation", "Artifact file manifest", "Artifact", True, True),
        ("docs/benchmark_spec.md", "documentation", "Benchmark specification", "Benchmark", True, True),
        ("docs/artifact_readme.md", "documentation", "Artifact README", "Artifact", True, True),
        ("docs/data_manifest.csv", "documentation", "Data file manifest", "Artifact", True, True),
        ("docs/schema_benchmark_items.json", "documentation", "Benchmark item schema", "Artifact", True, True),
        ("docs/schema_generations.json", "documentation", "Generation schema", "Artifact", True, True),
        ("docs/schema_metrics.json", "documentation", "Metric schema", "Artifact", True, True),
        ("src/prepare_review_artifact.py", "code", "Artifact generation script", "Artifact", True, True),
    ]
    for file_path, artifact_type, description, section, anonymous, required in definitions:
        entries.append({
            "file_path": file_path,
            "artifact_type": artifact_type,
            "description": description,
            "paper_section": section,
            "anonymous": str(anonymous).lower(),
            "required_for_reproduction": str(required).lower(),
        })
    write_csv(DOCS_DIR / "artifact_manifest.csv", entries, ["file_path", "artifact_type", "description", "paper_section", "anonymous", "required_for_reproduction"])


def main() -> None:
    for directory in [DATA_DIR, OUTPUTS_DIR, METRICS_DIR, FIG_DIR, DOCS_DIR]:
        directory.mkdir(parents=True, exist_ok=True)
    rows, raw_counts = load_all_rows()
    common_qids = shared_question_ids(rows)
    aligned_rows = [r for r in rows if r["question_id"] in common_qids]
    produce_alignment_report(rows, aligned_rows)
    produce_tables(aligned_rows, raw_counts)
    produce_figures(aligned_rows)
    produce_table_captions()
    produce_audit_and_cases(aligned_rows)
    produce_docs(rows, raw_counts)
    produce_schema_files()
    produce_manifest()
    print(f"generated review artifacts from {len(aligned_rows)} aligned parsed generations")
    print(f"shared question_id values: {len(common_qids)}")
    print("review materials written to docs/, fig_tabs/, metrics/, and src/")


if __name__ == "__main__":
    main()
